#!/usr/bin/env bash
DB_NAME=
DB_USER=
DB_PASS=
DB_HOST=
DB_PORT=
DJANGO_SUPERUSER_PASSWORD=123
DJANGO_SUPERUSER_USERNAME=admin
DJANGO_SUPERUSER_EMAIL=admin@admin.com

docker build --build-arg DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD} \
--build-arg DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME} \
--build-arg DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL} \
-t fastapi:base -f Dockerfile.base .

